### PR TITLE
Apalike output format

### PR DESCRIPTION
**Pull request by wleoncio**
# Summary

This PR addresses Issue #144 and implements an output format that loosely follows the guidelines set in the [_How to Cite Software in APA Style_](https://blog.apastyle.org/apastyle/2015/01/how-to-cite-software-in-apa-style.html) blog post.

# Motivation

The general idea of an APA-like format is not to rigidly follow [APA rules](https://apastyle.apa.org), but mostly to provide an output that resembles something that one would find in a scientific publication, particularly following the "usual who-when-what-where format". As posted on #144, I believe such output could be very useful for people wanting to cite software in less structured contexts (an e-mail, a pure-text document editor, etc.)

# Quality assurance

Unit tests have been implemented to make sure the presented commit passes all tests listed on the [README file](https://github.com/citation-file-format/cff-converter-python/blob/master/README.rst#running-tests). 

Nonetheless, I noticed my fork is currently failing the TravisCI versioning check due to "VersionConflict: (pytest 4.3.1 (/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages), Requirement.parse('pytest>=4.6'))". The output of a local run of `python3 -m pytest test/test_consistent_versioning.py` ends with all (4) tests passing in 0.09 s (`platform linux -- Python 3.6.9, pytest-5.3.5, py-1.8.1, pluggy-0.13.1`).

### CODE REVIEW

**Comment by wleoncio** [comment]
Please advise on how to address the [issue raised by Travis](https://travis-ci.org/github/citation-file-format/cff-converter-python/jobs/701628685).

**Comment by jspaaks** [comment]
Looks like the configuration needed some love. I've made some updates, e.g.
1. upgraded pytest version in requirements-dev.txt
1. upgraded the travis os to ubuntu 18.04
1. changed the set of supported python versions to [3.6, 3.7, 3.8]
1. changed from sonar-scanner on travis to sonarcloud github app

with these changes, travis is green for master branch.

You can get these changes by:

```shell
cd to your clone directory
git remote add upstream https://github.com/citation-file-format/cff-converter-python.git
git fetch upstream
git merge upstream/master
```

Let me know how you get on,
-Jurriaan

**Comment by wleoncio** [comment]
Fantastic, that was it. Thank you very much for the detailed help!

**Comment by jspaaks** [comment]
Very nicely done! Would you please extend this PR by adding yourself to cffconvert's CITATION.cff? Unless you'd rather not be listed, of course. Thanks!

**Comment by wleoncio** [comment]
> Very nicely done! Would you please extend this PR by adding yourself to cffconvert's CITATION.cff?

Sure thing, I'm honored!

**Comment by jspaaks** [comment]
:1st_place_medal:

**Pull request merged**
